import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import '../core/styles/index.scss';
import { Poppins } from 'next/font/google';
import { Providers } from './Providers';
const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={poppins.className}>
            <body className="bg-base">
                <ToastContainer />
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
